### ISSUE TITLE
Misleading title: library is not 2KB

### ISSUE THREAD

**Issue by paulmillr** [pur3miish/isomorphic-secp256k1-js#1]
```
cat private/index.mjs private/utils.mjs get_public_key.mjs sign.mjs | wc 
     282    1226    8228
```

If we only count get_public_key, sign and modules they import, it's 8228 aka 8KB.

**Comment by pur3miish** [comment]
Thanks 👍
The package was originally just for generating a signature, which was under the 2kb when GZIP I forgot to change the readme.
